export const allCourses = [
  {
    id: 1,
    slug: "itr-filing",
    name: "ITR Filing Course A.Y. 2025-26",
    price: 3199,
    originalPrice: 11999,
    img: "/images/courses/1.png",
    category: "Tax",
    rating: 4.5,
    instructor: {
      name: "CA Sudesh Kumar Gupta",
      avatar: "/images/instructors/sudesh.jpg", 
    },
    duration: "8H 20M",
    validity: "90 days",
    certificate: true,
    language: "Hindi and English",
    description: "A practical course on ITR filing for the latest Assessment Year. Learn the ins and outs of income tax returns for individuals and businesses.",
    whatYoullLearn: [
      "Understand different types of ITR forms.",
      "Accurately compute taxable income and file returns.",
      "Handle TDS, advance tax, and self-assessment tax.",
      "Learn about deductions under Chapter VI-A.",
    ],
    materialsIncluded: [
      "8+ Hours of HD videos",
      "Excel working notes",
      "Call & WhatsApp support",
      "Course completion certificate",
    ],
    requirements: ["No prior knowledge required."],
  },
  {
    id: 2,
    slug: "private-limited-company-registration",
    name: "Private Limited Company Registration",
    price: 3199,
    originalPrice: 8499,
    img: "/images/courses/2.png",
    category: "Business",
    rating: 4.2,
    instructor: {
      name: "CA Sudesh Kumar Gupta",
      avatar: "/images/instructors/sudesh.jpg", 
    },
    duration: "5H 15M",
    validity: "Lifetime Access",
    certificate: true,
    language: "English",
    description: "Learn the complete process of registering a Private Limited Company in India, from documentation to final certification.",
    whatYoullLearn: [
      "Understand the legal framework for company registration.",
      "Prepare all necessary documentation (MOA, AOA).",
      "Navigate the MCA portal and file SPICe+ forms.",
      "Post-incorporation compliances.",
    ],
    materialsIncluded: [
      "5+ Hours of HD videos",
      "Document templates",
      "Step-by-step guides",
      "Course completion certificate",
    ],
    requirements: ["No prior legal knowledge required."],
  },
  {
    id: 3,
    slug: "udyam-registration-course",
    name: "Udyam Registration Course",
    price: 1499,
    originalPrice: 5199,
    img: "/images/courses/3.png",
    category: "Business",
    rating: 4.8,
    instructor: {
      name: "CA Sudesh Kumar Gupta",
      avatar: "/images/instructors/sudesh.jpg", 
    },
    duration: "2H 00M",
    validity: "Lifetime Access",
    certificate: true,
    language: "English",
    description: "A complete guide to MSME Udyam registration, covering benefits, eligibility, and the step-by-step online process.",
    whatYoullLearn: [
      "Understand the benefits of Udyam registration.",
      "Check eligibility criteria for your business.",
      "Complete the online registration process without errors.",
      "Download and manage your Udyam certificate.",
    ],
    materialsIncluded: [
      "2 Hours of HD videos",
      "Step-by-step PDF guide",
      "Lifetime course access",
      "Course completion certificate",
    ],
    requirements: ["Aadhaar number and business details."],
  },
  {
    id: 4,
    slug: "company-annual-filing",
    name: "Company Annual Filing",
    price: 1799,
    originalPrice: 6499,
    img: "/images/courses/4.png",
    category: "Finance",
    rating: 4.7,
    instructor: {
      name: "CA Sudesh Kumar Gupta",
      avatar: "/images/instructors/sudesh.jpg",
    },
    duration: "10H 30M",
    validity: "1 Year Access",
    certificate: true,
    language: "Hindi and English",
    description: "Master the annual compliance requirements for private limited companies and LLPs. This course covers everything from board meetings to annual filings.",
    whatYoullLearn: [
      "Conducting Board Meetings and AGMs.",
      "Drafting resolutions and minutes.",
      "Filing forms like MGT-7 and AOC-4.",
      "Understanding director responsibilities.",
    ],
    materialsIncluded: [
      "10+ Hours of HD videos",
      "Detailed PDF Notes",
      "Checklists and templates",
      "Call & WhatsApp support",
      "Course completion certificate",
    ],
    requirements: ["Basic knowledge of corporate law is beneficial."],
  },
];

// This function is used by your dynamic [slug] page to find the correct course.
export const getCourseBySlug = (slug) => {
  return allCourses.find((course) => course.slug === slug);
};